ktor:
    application:
        modules:
            - me.rayatnia.ApplicationKt.module
    deployment:
        port: ${PORT:8080}

database:
    url: "jdbc:postgresql://${POSTGRES_URL}/allride"
    driver: "org.postgresql.Driver"
    user: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:AllRide2024!}

cache:
    memcached:
        endpoint: ${MEMCACHED_ENDPOINT:localhost:11211}
        connectionPoolSize: 2
        operationTimeout: 3000

aws:
    region: ${AWS_REGION:us-east-1}
    sqs:
        mainQueueUrl: ${SQS_QUEUE_URL}
        dlqUrl: ${SQS_DLQ_URL}
